import type { Metadata } from "next";
import { Noto_Sans, Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
 weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Udemy Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Apply the variables to the html or body tag
    <html lang="en" className={`${notoSans.variable} ${vazirmatn.variable}`}>
      <body className="antialiased font-sans ">
        <Navbar />
        <div className="px-6 py-4 md:px-12 md:py-6 lg:px-24 lg:py-8">
        {children}
         </div>
        <Footer />
       
      </body>
    </html>
  );
}